apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    {{- include "mysql-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "mysql-chart.selectorLabels" . | nindent 4 }}
