---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress-chart.fullname" . }}
  labels:
    {{- include "wordpress-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

